insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Chev Mordaunt', 'Charing Cross', '1994-07-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Charlie Hamor', 'Prairieview', '1995-05-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Laird Twinbrow', 'David', '1993-06-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Anabel Gingedale', 'Coolidge', '1997-03-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Eugenio Cholwell', 'Mcbride', '1994-02-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Mellicent Flores', 'Nelson', '1999-06-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Marlowe Aylott', 'Susan', '1997-10-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Pierre Pinxton', 'Anthes', '1997-02-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Humberto Ferson', 'East', '1993-01-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Boycey Buxey', 'Spaight', '1990-12-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Harmony Rabbe', 'Prentice', '1999-08-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Lona Lago', 'Westport', '1998-05-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Shaine Tenny', 'Esch', '1997-08-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Nanni Pudsey', 'Canary', '1995-01-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rollins Pirnie', 'Donald', '1991-06-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Horacio Cubbino', 'Old Shore', '1992-09-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Muffin Blanko', 'Trailsway', '1994-03-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sigfried Kondratowicz', 'Heffernan', '1990-04-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Erma Leguay', 'Loeprich', '1990-11-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Erwin Sprosson', 'Dexter', '1998-02-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Julissa Critchley', 'Bartelt', '1993-07-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kris Emilien', 'Portage', '1990-05-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Alissa Polle', 'Old Gate', '1994-12-31');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Lorilee Feild', 'Katie', '1994-12-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Corney Windross', 'Barby', '1992-07-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ardine Barneville', 'Superior', '1993-06-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Peggie Trathen', 'Starling', '1993-12-04');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Drucy Connar', 'Warbler', '1990-10-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sheilakathryn Swayland', 'Hanson', '1999-10-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sula Endricci', 'Butternut', '1991-01-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Erastus Maroney', 'Coleman', '1995-10-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Titos Rolfi', 'Gulseth', '1996-11-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ysabel Hatter', 'Lien', '1992-06-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gloriane Wadman', 'Morning', '1990-04-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Wilie Wixey', 'Vera', '1991-12-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Katha Niccols', 'Butternut', '1990-04-04');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Krystalle Airlie', 'Bluestem', '1999-11-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Danella Aiton', 'Donald', '1998-03-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Hallie Chiverstone', 'Reinke', '1997-10-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dorice Thornbarrow', 'Sachs', '1991-12-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Tommie Yashin', 'Lerdahl', '1995-06-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ancell Murrock', 'Jackson', '1999-01-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Boyd Thurnham', 'Lukken', '1995-10-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Daven Grist', 'Pond', '1991-08-31');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Vaclav Noades', 'Crownhardt', '1998-02-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gavra Kiddy', 'Main', '1994-05-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Randolf Jumonet', 'Duke', '1998-09-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Fulvia Hurkett', 'Spaight', '1995-10-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Wilfrid Bodd', 'Onsgard', '1998-09-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sayre Dudson', 'Jay', '1997-03-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Tammi Baysting', 'Melody', '1991-04-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Derril Zorener', 'Onsgard', '1997-02-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Mikey Hyde-Chambers', 'Ilene', '1992-03-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Greggory Coggeshall', 'New Castle', '1993-09-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Madella Blackley', 'Dakota', '1990-05-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Eulalie Andersch', 'Bartillon', '1998-12-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Paxton Ferfulle', 'Dunning', '1997-10-31');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ivette Almey', 'Sutteridge', '1990-04-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Cyndia Maestro', 'Transport', '1993-07-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Shaina Loudiane', 'Cody', '1992-12-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ripley McEwen', 'Ilene', '1993-06-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Tally Brunker', 'Mariners Cove', '1990-05-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Cornell Mockes', 'Kinsman', '1999-06-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Langsdon Dunphie', 'Buena Vista', '1999-02-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Viva Matiewe', 'Delaware', '1992-07-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Purcell Linster', 'Starling', '1992-03-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Leonanie Mugglestone', 'Blackbird', '1994-06-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Goran Walster', 'Becker', '1998-07-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kai Mays', 'Loomis', '1991-02-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Pippa Lghan', 'Hintze', '1995-02-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dodi Sarjeant', 'Summer Ridge', '1996-07-31');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Claudia Brookfield', 'Del Mar', '1995-06-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Emmit Cronin', 'Larry', '1994-01-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Andros Whate', 'Ryan', '1992-02-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Norean Clinnick', 'Florence', '1990-11-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Shana Crichley', 'Charing Cross', '1997-07-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Fidela Frenchum', 'Muir', '1990-05-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Blakeley Donnett', 'Bayside', '1999-06-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Janaya Boothebie', 'Brentwood', '1991-02-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dex Huitt', 'Washington', '1992-03-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sara Tzar', 'Old Shore', '1995-12-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gottfried Lortz', 'Welch', '1999-08-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Menard Gabotti', 'Cardinal', '1998-05-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Biron McAster', 'Arizona', '1997-06-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Keen Brydie', 'Badeau', '1998-03-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Mervin Imason', 'Dexter', '1992-11-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Alberik Zuann', 'Morningstar', '1993-02-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Meir Reoch', 'Stuart', '1995-06-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jamison Nicklinson', 'Bluestem', '1999-10-31');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kessia Maddyson', 'Grim', '1993-03-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jory MacNalley', 'Service', '1993-01-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Isis Litchmore', 'Stephen', '1990-07-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Pollyanna Emanueli', 'Heffernan', '1998-07-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jaymee Housin', 'Spaight', '1994-12-04');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sosanna Keenlayside', 'Algoma', '1998-04-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Madelena Tofpik', 'Shelley', '1997-12-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Avery Sawood', 'Wayridge', '1997-07-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Adolphus Bucher', 'Sunfield', '1992-12-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Cherrita Terzza', 'Prairieview', '1990-05-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Caroljean Crankhorn', 'Menomonie', '1992-05-26');
